MONGO_URI = "mongodb+srv://martinjauma:streamlit@segirlogingoogle.uf2etwv.mongodb.net/?retryWrites=true&w=majority"


[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "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"
client_id = "477019567977-illolehtmihhflq91rrebadvulern71m.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"


